name: Netty Test Workflow
on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster name'
        default: 'bal-perf-cluster'
        required: false
jobs:
  setup:
    strategy:
      max-parallel: 1
      matrix:
        count: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
        payload: [ 50 ]
        users: [ 1 ]
    runs-on: ubuntu-latest
    env:
      TEST_NAME: "netty_hello"
      TEST_ROOT: "tests"
    timeout-minutes: 600
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Deploy artifacts
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl utils write-kubeconfig --cluster="${{ github.event.inputs.clusterName }}"
        kubectl apply -f ${TEST_ROOT}/${TEST_NAME}/k8s.yaml

    - name: Write values to outputs
      id: write
      run: |
        host=`kubectl get svc nginx-ingress-ingress-nginx-controller --namespace ingress-basic -o=go-template --template='{{(index .status.loadBalancer.ingress 0 ).hostname}}'`
        IP=`nslookup $host |  awk '{if (NR==6) {print $2}}'`
        user_data_file=$(mktemp /tmp/user-data-XXXX.txt)
        cat <<EOF >$user_data_file
        #cloud-config
        system_info:
          default_user:
            name: bal-admin
        EOF
        INSTANCE_ID=$(aws ec2 run-instances --user-data file://$user_data_file  --image-id ami-090717c950a5c34d3 --count 1 --instance-type c6g.2xlarge --key-name ballerina-jmeter-vm --security-groups ballerina-jmeter-sg --output text --query 'Instances[*].InstanceId')
        while STATE=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --output text --query 'Reservations[*].Instances[*].State.Name'); test "$STATE" != "running"; do
            sleep 1;
        done;
        aws ec2 wait instance-status-ok
        DNS=$(aws ec2 describe-instances --instance-ids ${INSTANCE_ID} --output text --query 'Reservations[*].Instances[*].PublicDnsName')
        echo "Ingress IP: $IP"
        echo "::set-output name=cluster-ip::$IP"
        echo "::set-output name=scenario-name::${TEST_NAME}"
        echo "::set-output name=git-token::${{ secrets.BALLERINA_BOT_TOKEN }}"
        echo "::set-output name=instance-id::$INSTANCE_ID"
        echo "::set-output name=dns-name::$DNS"
    - name: Execute performance tests
      uses: appleboy/ssh-action@master
      env:
        IP: ${{ steps.write.outputs.cluster-ip }}
        SCENARIO_NAME: ${{ steps.write.outputs.scenario-name }}
        PAYLOAD: ${{ matrix.payload }}
        USERS: ${{ matrix.users }}
      with:
        host: ${{ steps.write.outputs.dns-name }}
        username: bal-admin
        key: ${{ secrets.SSH_KEY }}
        envs: IP,SCENARIO_NAME,PAYLOAD,USERS
        command_timeout: '180m' #3 hours
        timeout: 300s #5 mins
        script: |
          git clone https://github.com/xlight05/ballerina-performance-cloud
          sudo cp -r ballerina-performance-cloud/base-image /
          sudo chmod -R 777 /base-image
          sh /base-image/init.sh
          source /etc/profile.d/10-perf-vm.sh
          execute-tests.sh -c $IP -s $SCENARIO_NAME -p $PAYLOAD -u $USERS
    - name: Clean up resources
      env:
        INSTANCE_ID: ${{ steps.write.outputs.instance-id }}
      run: |
         aws ec2 terminate-instances --instance-ids ${INSTANCE_ID}
#         eksctl delete cluster "${{ github.event.inputs.clusterName }}"-"${{ matrix.count }}"