name: remote ssh command
on:
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Execute Tests
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}
      run: |
        echo "$SSH_KEY" > ballerina-jmeter-vm.pem
        chmod 400 ballerina-jmeter-vm.pem
        mkdir -p /home/runner/.ssh
        INSTANCE_ID="i-0d612d6328f4bbedc"
        # $(aws ec2 run-instances --image-id ami-055d9171bb70733a3 --count 1 --instance-type c5.xlarge --key-name ballerina-jmeter-vm --security-groups ballerina-jmeter-sg --output text --query 'Instances[*].InstanceId')
        aws ec2 wait instance-status-ok
        DNS=$(aws ec2 describe-instances --instance-ids ${INSTANCE_ID} --output text --query 'Reservations[*].Instances[*].PublicDnsName')
        if [ -z "$(ssh-keygen -F $DNS)" ]; then
          ssh-keyscan -H $DNS >> ~/.ssh/known_hosts
        fi
        ssh -i ballerina-jmeter-vm.pem ubuntu@${DNS} "rm -r ballerina-performance-cloud && source /etc/profile.d/10-perf-vm.sh && execute-tests.sh -c $IP -s $SCENARIO_NAME -p $PAYLOAD -u $USERS"
