name: SSH_Workflow

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster name'
        default: 'bal-perf-cluster-test'
        required: false
jobs:
  setup:
    strategy:
      max-parallel: 1
      matrix:
        payload: [ 50 ]
        users: [ 60 ]
    runs-on: ubuntu-latest
    env:
      TEST_NAME: "test_passthrough"
      TEST_ROOT: "tests"
    timeout-minutes: 600
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: "ec2-35-80-15-212.us-west-2.compute.amazonaws.com"
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        command_timeout: '180m' #3 hours
        timeout: 300s #5 mins
        script: |
          git clone https://github.com/ballerina-platform/ballerina-performance-cloud
          sudo cp -r ballerina-performance-cloud/base-image /
#          sudo chmod -R 777 /base-image
          sh /base-image/init.sh
          source /etc/profile.d/10-perf-vm.sh
          execute-tests.sh -c "35.161.9.222" -s "test_passthrough" -p 50 -u 60
